# Info from: https://github.com/gitpod-samples/template-dotnet-core-cli-csharp/blob/master/.gitpod.yml 
#   &  https://www.gitpod.io/docs/introduction/languages/dotnet
image: gitpod/workspace-dotnet-vnc:latest

# tasks:
#   - name: Restore & Build
#     init: |
#       dotnet dev-certs https 
#       dotnet restore
#       dotnet build
#   - name: Run
#     command: dotnet run

vscode:
  extensions:
    - muhammad-sammy.csharp