// <auto-generated />
namespace DDDPPP.Chap21.EFExample.Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class yoyo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(yoyo));
        
        string IMigrationMetadata.Id
        {
            get { return "202408171915573_yoyo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
